pipeline {
    agent { label 'agent-mac' }

    stages {
        stage('Install Dependencies') {
            steps {
                echo 'Installing Python dependencies...'
                script {
                    sh 'pwd && ls -la && pip install -r requirements.txt'
                }
            }
        }

        stage('Run Unit Tests') {
            steps {
                script {
                    sh '''
                    cd unit_tests
                    python -m unittest discover -s . -v
                    '''
                }
            }
        }
    }
}



