pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                echo 'Installing Python dependencies...'
                script {
                    sh 'sw_vers'
                    sh 'pwd'
                    sh 'ls -la'
                    sh 'pip install -r requirements.txt"'
                }
            }
        }
    }
}


