pipeline {
    agent { label 'agent-mac' }

    stages {
        stage('Run Tests Across Python Versions') {
            matrix {
                axes {
                    axis {
                        name 'PYTHON_VERSION'
                        //values 'python3.11', 'python3.12'
                        values 'python3.12'
                    }
                }
                stages {
                    stage('Setup and Test') {
                        steps {
                            echo "Setting up virtual environment with ${PYTHON_VERSION}..."
                            script {
                                sh """
                                # Creating a virtual environment with the specified Python version
                                ${PYTHON_VERSION} -m venv myenv-${PYTHON_VERSION}
                                source myenv-${PYTHON_VERSION}/bin/activate

                                # Install dependencies
                                ${WORKSPACE}/myenv-${PYTHON_VERSION}/bin/pip install -r requirements.txt

                                # Run tests using nose2 with coverage
                                ${WORKSPACE}/myenv-${PYTHON_VERSION}/bin/nose2 -v --with-coverage unit_tests

                                # Generate XML coverage report
                                ${WORKSPACE}/myenv-${PYTHON_VERSION}/bin/coverage xml -o coverage.xml
                                """
                            }
                        }
                    }
                }
                post {
                    always {
                        junit 'reports/*.xml'  // For test reports
                        cobertura coberturaReportFile: 'coverage.xml'  // For coverage reports
                    }
                }
            }
        }
    }
}
