name: Run Testing

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    environment: AWS

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unittests with nose2 and generate coverage report
        run: |
          nose2 -v --with-coverage unit_tests
          coverage json -o coverage.json  # Generate JSON coverage report

      - name: Publish Test Results (This GitHub Action analyses test result files and publishes the results on GitHub)
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: test-results
        if: always()
        with:
          files: "reports/*.xml"
      - name: Call Send Reports to Grafana
        uses: ./.github/workflows/send-reports-to-grafana.yml
        with:
          commit: "${{ github.event.head_commit.message }}"
          author: "${{ github.event.pusher.name }}"
          path_to_junit_reports: "reports/junit-report.xml"
          test_level: "unit"
